<?php

declare(strict_types=1);

namespace App\Tests\Unit;

use App\Greetings;
use PHPUnit\Framework\TestCase;

class GreetingsTest extends TestCase
{

    private Greetings $greetings;

    protected function setUp(): void
    {
        parent::setUp(); 
        $this->greetings = new Greetings();
    }
    
    protected function tearDown(): void
    {
        parent::tearDown();
        unset($this->greetings);
    }
    
    static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass();
    }
    
    static function tearDownAfterClass(): void
    {
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }

    /**
     * @return Greetings
     * @test
     */
    public function it_is_instance_of_an_object()
    {
        
        self::assertInstanceOf(Greetings::class, $this->greetings);
        
        return $this->greetings;
    }
    
    /**
     * @test
     * @depends it_is_instance_of_an_object
     */
    public function it_should_return_greetings_text(Greetings $greetings): void
    {
        self::assertSame("Hello Marek", $greetings->hello("Marek"));
    }
}
